### ISSUE TITLE
Copy output with all the package that have the same name root

### ISSUE THREAD

**Issue by mach22** [baseclass/Contrib.Nuget#13]
I have made 2 nuget packaget
"MyPackage.nupkg" that contains only the lib folder with the dll to add to the project
"MyPackage.Output.nupkg" that depends from the first package and plus add the output folder where are some other files.

When I make a project that reference only the first package but in the global solution packages folder is downloaded even the second package even the otput files of the second package are copied to the output of the project even it the project refer only the first package.

**Comment by romerod** [comment]
@arcamab fixed this, the fix is availabe in Version 1.0.9
