### ISSUE TITLE
Not compile if there is no packages other Nuget package with output folder

### ISSUE THREAD

**Issue by mach22** [baseclass/Contrib.Nuget#15]
I have made a new project, add the Nuget Package Baseclass.Contrib.Nuget.Output.1.0.9 and no other one, the project not compile with this error:

Error   1   Invalid static method invocation syntax: "[System.IO.Path]::GetFullPath()". Method 'System.IO.Path.GetFullPath' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).    NUget

**Comment by romerod** [comment]
ok, thanks this might not be perfect, but it doesn't make sense to use it that way, it only makes sense to use it as a dependendency of package.

I leave the issue open eitherway

**Comment by mach22** [comment]
Sure, but when a nuget package depend on this package it add even this as a dependency, and when it is removed if the derived package desn't remove even this package the project doesn't compile, this is quite absurd, this is a prerequisite that if it is installed alone doesn't make compiling the project ?!?!?

**Comment by romerod** [comment]
When you remove the dependent package it usually asks you to remove this package as well.

It's an issue, I just wanted to tell you that this usage doesn't make sense


-------- Ursprüngliche Nachricht --------
Von: mach22 <notifications@github.com>
Datum: 04.05.2015 22:14 (GMT+01:00)
An: "baseclass/Contrib.Nuget" <Contrib.Nuget@noreply.github.com>
Cc: Daniel Romero <daniel.romero@baseclass.ch>
Betreff: Re: [Contrib.Nuget] Not compile if there is no packages other Nuget package with output folder (#15)


Sure, but when a nuget package depend on this package it add even this as a dependency, and when it is removed if the derived package desn't remove even this package the project doesn't compile, this is quite absurd, this is a prerequisite that if it is installed alone doesn't make compiling the project ?!?!?

-

**Comment by mnivet** [comment]
I've also experiment this issue after having reintegrate in my fork the pull request #14.
Try version 2.0.0 it should resolve this problem among other ones

**Comment by romerod** [comment]
@mach22 is this solved?
