### ISSUE TITLE
Visual Studio 2015 RC

### ISSUE THREAD

**Issue by bitbeans** [baseclass/Contrib.Nuget#17]
Baseclass.Contrib.Nuget.Output "currently" fails on VS 2015 RC.
With the current CodeTaskFactory 

```xml
<UsingTask TaskName="PackageFilter" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v$(MSBuildToolsVersion).dll">
```
it will generate the following path:

>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Build.Tasks.v14.0.dll

The problem is that the file apparently no longer exists in MSBuild 14.

The following change will fix this problem in VS 2015:

```xml
<UsingTask TaskName="PackageFilter" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
```

and produce:

>C:\Program Files (x86)\MSBuild\14.0\Bin\Microsoft.Build.Tasks.Core.dll

**Comment by EnriGrossi** [comment]
My pull request should fix this.

Enri
