### ISSUE TITLE
Baseclass.Contrib.Nuget.GitIgnoreContent Install generates error with VS2015 / Nuget 3

### ISSUE THREAD

**Issue by Zardozz** [baseclass/Contrib.Nuget#23]
With 
Microsoft Visual Studio Enterprise 2015
Version 14.0.23107.0 D14REL

and Nuget Package manager 3.1.60724.766 Extension (Package Manager Console Host Version 3.1.1.0)

Running "Install-Package Baseclass.Contrib.Nuget.GitIgnoreContent" generates the following error:-

Executing script file 'C:\Users\a\project\packages\Baseclass.Contrib.Nuget.GitIgnoreContent.0.0.2\tools\init.ps1'
Unable to find type [NuGet.VisualStudio.IVsPackageInstallerEvents].
At C:\Users\a\project\packages\Baseclass.Contrib.Nuget.GitIgnoreContent.0.0.2\tools\GitIgnoreNugetContentRegisterEvents.ps1:7 char:1
+ $packageInstallerEvents = $componentModel.GetService([NuGet.VisualStu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (NuGet.VisualStu...InstallerEvents:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
Register-ObjectEvent : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Users\a\project\packages\Baseclass.Contrib.Nuget.GitIgnoreContent.0.0.2\tools\GitIgnoreNugetContentRegisterEvents.ps1:10 char:64
+ ... ntRegistration = Register-ObjectEvent $packageInstallerEvents Package ...
+                                           ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Register-ObjectEvent], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.RegisterObjectEventCommand
 
Register-ObjectEvent : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Users\a\project\packages\Baseclass.Contrib.Nuget.GitIgnoreContent.0.0.2\tools\GitIgnoreNugetContentRegisterEvents.ps1:21 char:66
+ ... ntRegistration = Register-ObjectEvent $packageInstallerEvents Package ...
+                                           ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Register-ObjectEvent], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.RegisterObjectEventCommand
 
Successfully installed 'Baseclass.Contrib.Nuget.GitIgnoreContent 0.0.2' to project

My first guess is that this is due to a change in Nuget v3 as I have successfully used this package on a VS2013 / Nuget 2.8.6 based project

**Comment by romerod** [comment]
I personally recommend to use a package manager like bower for javascript dependencies, if you like to contribute send me a pull request.

It seems like something in the VisualStudio 2015 automation changed.
