### ISSUE TITLE
Baseclass.Contrib.Nuget.Output.targets (73): An error has occurred during compilation

### ISSUE THREAD

**Issue by Liero** [baseclass/Contrib.Nuget#26]
Please, have a look here: http://stackoverflow.com/questions/35176910/nuget-copy-native-dll-into-output

When I try to build project that contains nuget dependent on `Baseclass.Contrib.Nuget.Output 2.1.0` I get following errors:

> C:\Builds\1\MyProject\BuildName\src\MyProject\Packages\Baseclass.Contrib.Nuget.Output.2.1.0\build\net40\Baseclass.Contrib.Nuget.Output.targets (73): 
> The source file for this compilation can be found at: "C:\Users\MHABLDSvc\AppData\Local\Temp\fd4f7f9d-59e3-4f6a-af8c-6a48deb7af3e.txt"

> C:\Builds\1\MyProject\BuildName\src\MyProject\Packages\Baseclass.Contrib.Nuget.Output.2.1.0\build\net40\Baseclass.Contrib.Nuget.Output.targets (73):
> An error has occurred during compilation. error CS1705: Assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' uses 'Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

> C:\Builds\1\MyProject\BuildName\src\MyProject\Packages\Baseclass.Contrib.Nuget.Output.2.1.0\build\net40\Baseclass.Contrib.Nuget.Output.targets (73): 
> The "PackageFilter" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\MSBuild\14.0\bin\amd64" directory.

> C:\Builds\1\MyProject\BuildName\src\MyProject\Packages\Baseclass.Contrib.Nuget.Output.2.1.0\build\net40\Baseclass.Contrib.Nuget.Output.targets (73):
> An error has occurred during compilation. error CS1705: Assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' uses 'Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

> C:\Builds\1\MyProject\BuildName\src\MyProject\Packages\Baseclass.Contrib.Nuget.Output.2.1.0\build\net40\Baseclass.Contrib.Nuget.Output.targets (73): 
> The "PackageFilter" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\MSBuild\14.0\bin\amd64" directory.

**Comment by jaredbroad** [comment]
@Liero I had a similar error and we think it disappeared by upgrading Visual Studio. 2.1.0 was in VS2012, 2.1.0.1 was build in VS2013.

**Comment by romerod** [comment]
@Liero could you try the latest https://www.nuget.org/packages/Baseclass.Contrib.Nuget.Output/2.2.0-xbuild02
