### ISSUE TITLE
Support packages.{project-name}.config files

### ISSUE THREAD

**Issue by 4cc8783b** [baseclass/Contrib.Nuget#28]
According to the NuGet FAQ, packages.config may be named packages.{project-name}.config (see https://docs.nuget.org/consume/nuget-faq "I have multiple projects in the same folder, how can I use separate packages.config or project.json files for each project?").

Baseclass.Contrib.Nuget.Output does only look for a packages.config file. I don't know, if the other extensions have the same behaviour.
I use both possibilities to name the packages.config file in my projects and would be happy to see both of them supported, hence I want to use your extension to NuGet (at least the Baseclass.Contrib.Nuget.Output extension).

Cheers,
Dome

**Comment by romerod** [comment]
Could you try this package:
https://www.nuget.org/packages/Baseclass.Contrib.Nuget.Output/2.2.0-xbuild01
