### ISSUE TITLE
Visual Studio 2017 RC build error

### ISSUE THREAD

**Issue by marcbarry** [baseclass/Contrib.Nuget#31]
Having the nuget package of this project (version 2.1.0) installed to a project in Visual Studio 2017 RC prevents build from completing with the following error:

`Error The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Build.Tasks.v15.0.dll". Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Build.Tasks.v15.0.dll' or one of its dependencies. The system cannot find the file specified.`

Any ideas?

**Comment by romerod** [comment]
Could you try with the latest prerelease package?


https://www.nuget.org/packages/Baseclass.Contrib.Nuget.Output/2.2.0-xbuild02

[https://nuget.org/Content/Images/packageDefaultIcon.png]<https://www.nuget.org/packages/Baseclass.Contrib.Nuget.Output/2.2.0-xbuild02>

NuGet Gallery | Baseclass.Contrib.Nuget.Output 2.2.0-xbuild02<https://www.nuget.org/packages/Baseclass.Contrib.Nuget.Output/2.2.0-xbuild02>
www.nuget.org
Contact Us. Got questions about NuGet or the NuGet Gallery? Overview. NuGet is a Visual Studio extension that makes it easy to add, remove, and update libraries and...




________________________________
Von: Marc Barry <notifications@github.com>
Gesendet: Freitag, 18. November 2016 00:47:00
An: baseclass/Contrib.Nuget
Betreff: [baseclass/Contrib.Nuget] Visual Studio 2017 error (#31)


Having the nuget package of this project (version 2.1.0) installed to a project in Visual Studio 2017 RC prevents build from completing with the following error:

Error The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Build.Tasks.v15.0.dll". Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Build.Tasks.v15.0.dll' or one of its dependencies. The system cannot find the file specified.

Any ideas?

-

**Comment by marcbarry** [comment]
The prerelease package seems to resolve the issue, thank you very much!

**Comment by mattmorg55** [comment]
Why isn't the VS 2017 installer updating the version of Baseclass.Contrib.Nuget.Output to 2.3 at this point? Or is this considered out of scope the VS installer?
