### ISSUE TITLE
The "PackageRetrievalTask" task failed unexpectedly

### ISSUE THREAD

**Issue by omatrot** [baseclass/Contrib.Nuget#33]
Using the latest prerelease version of the nuget in both VS 2015 & VS 2017 I have the following error during compilation.

> The "PackageRetrievalTask" task failed unexpectedly.
1>D:\CUSTOM_PATH\packages\Baseclass.Contrib.Nuget.Output.2.3.0-vs20172\build\net40\Baseclass.Contrib.Nuget.Output.targets(65,5): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path blablabla\packages'.

CUSTOM_PATH & blablabla above are obfuscation of real paths.

Please note that we're sharing packages at the root of our TFS branch. 
The task seems to look for packages in the solution folder.

We do have a repositoryPath configured in a nuget.config at solution level:
`<add key="repositorypath" value="$\..\..\..\..\..\packages" />`

.csproj included.
[csproj.zip](https://github.com/baseclass/Contrib.Nuget/files/861511/csproj.zip)

**Comment by loicmorvan** [comment]
I have the same issue: we put the packages at the root of our branches in a special folder named 'ThirdParties' and not 'packages' but it looks for 'packages'.

**Comment by loicmorvan** [comment]
@omatrot For now, I can just use the version "v2.2.0-xbuild02" which works well waiting for an new update.

**Comment by DuAell** [comment]
Issue still alive in v2.3.0

**Comment by shauser** [comment]
I just created PR #38, but missed this way of specifying the repo path. I'll update the PR real quick to add support for this setting as well.

**Comment by fabiosalvi** [comment]
@omatrot @loicmorvan @DuAell @shauser see issue #39

**Comment by romerod** [comment]
PR merged

**Comment by omatrot** [comment]
This works only we you case the config parameter name correctly.
In the sample I've given above, `repositorypath` is lower case. It still fails. 
It works with an uppercase P for path: `repositoryPath`.
