### ISSUE TITLE
fails to clean old data from /packages when updating from '2.2.0-xbuild02' to '2.3.0'

### ISSUE THREAD

**Issue by fabiosalvi** [baseclass/Contrib.Nuget#39]
In Visual Studio 2017, I've used the built-in NuGet to update packages from '2.2.0-xbuild02' to '2.3.0', but after that I couldn't build the project anymore ("PackageRetrievalTask" fails).

The problem is that in /packages, after update, the folder "Baseclass.Contrib.Nuget.Output.2.2.0-xbuild02" and the file "Baseclass.Contrib.Nuget.Output.2.2.0-xbuild02.deleteme" do not get deleted due to the problem shown in the pic.

![nuget](https://user-images.githubusercontent.com/29264173/29172779-53e7e01e-7de1-11e7-9e98-740eb50ee2ac.jpg)

Removing folder and file manually and rebuilding solves all issues.

This could be the problem at the bottom of issues #33 - #34 - #35

**Comment by romerod** [comment]
Thank you for the taking the time to describe the problem.

This is due to the fact that visual studio uses the dll and doesn't let nuget delete it. The other issues #33 #34 #35 are not related. As I can't do anything about that i'm going to close it.
