### ISSUE TITLE
[PAKET] cannot use when sln file is not in the same directory as paket.dependencies file

### ISSUE THREAD

**Issue by somdoron** [baseclass/Contrib.Nuget#40]
Paket is usually at the root git directory and sln file is usually within src directory. The way the code resolve if the project is using paket is by looking at the sln directory for paket.dependecies.

I suggest also looking for the paket.dependencies file at the top git directory (if that is possible) or at the parent directory of the sln file

**Comment by romerod** [comment]
Ok, we could check for the existance of the paket.references file in the project directory instead, would that work on your case?

**Comment by somdoron** [comment]
yes, but we also have to fix the code that checks the paket.lock:

https://github.com/baseclass/Contrib.Nuget/blob/a00863d640aa8e656e9371957bb532d7d6662080/Baseclass.Contrib.Nuget.Output/Baseclass.Contrib.Nuget.Output.Build/PaketPackageManager.cs#L40

and also here:

https://github.com/baseclass/Contrib.Nuget/blob/a00863d640aa8e656e9371957bb532d7d6662080/Baseclass.Contrib.Nuget.Output/Baseclass.Contrib.Nuget.Output.Build/PaketPackageManager.cs#L27

**Comment by romerod** [comment]
That one can traverse the directory tree, at that point we know that there must be one.

Are you using the package?
________________________________

**Comment by somdoron** [comment]
That will work, thank you.
Yes, I'm both using the library in my own package and consume it.

my package:
https://www.nuget.org/packages/zen_secp256k1_linux/

I also plan to have one for windows and one for osx which copy the native library to the output directory.

I can submit the pull request later today if you want.

**Comment by romerod** [comment]
Happy to accept the PR
________________________________
