### ISSUE TITLE
It seems Baseclass.Contrib.Nuget.Output package 2.4.1 was built from wrong code base

### ISSUE THREAD

**Issue by nzapolski** [baseclass/Contrib.Nuget#43]
Please check decompiled code. There are no the latest classes
![image](https://user-images.githubusercontent.com/355062/33386976-370e67ac-d53d-11e7-970d-eb8b8cd889fc.png)

**Comment by somdoron** [comment]
I also suffer from same problem, any chance for new version?

**Comment by acailly** [comment]
I just compiled from sources and I confirm the package is different. It would be nice to have the new version on nuget, the paket features are very useful

**Comment by romerod** [comment]
Sorry, for the inconvinience, 2.4.2 contains the latest sources
